In [1]:
import numpy as np
import sympy as sp
from math import inf

## Codigo para escalonado de matrices

In [12]:
def i_non_null(R):
    """
    Find the index of the first non-null element in a row.

    Args:
        R (numpy.ndnp.array): The row.

    Returns:
        int: The index of the first non-null element.
    """
    # Use argmax to find the index of the first non-zero element
    i = np.argmax(R != 0)

    return i if R[i] != 0 else inf

def is_echelon_form(M):
    """
    Check if a matrix is in echelon form.

    Args:
        M (numpy.ndnp.array): The matrix.

    Returns:
        bool: True if the matrix is in echelon form, False otherwise.
    """
    # TODO: Revert changes
    # Iterate through the rows of the matrix, except last
    for i in range(M.shape[0] - 1):
        c_r = M[i] # Current row
        n_r = M[i + 1] # Next row

        c_r_nnv = np.argmax(c_r != 0) # Index current row first non null val
        n_r_nnv = np.argmax(n_r != 0) # Index next row first non null val

        # If the rows are null, means that the end of the matrix is reached, so is no need to verify nothing
        # The matrix is in echelon form
        if np.all(c_r == 0) and np.all(n_r == 0):
            return True

        # The first non-zero element of a row must be at the left of the first non-zero element of the next row.
        if c_r_nnv >= n_r_nnv:
            return False

    return True

def pivot_row_index(M, i, j):
    """
    Find the index of the row with the pivot element.

    Args:
        M (numpy.ndnp.array): The matrix.
        i (int): The current row index.
        j (int): The current column index.

    Returns:
        int: The index of the row with the pivot element.
    """
    mi_val = inf
    mi_i = None
    for n in range(i, len(M)):
        row = M[n]
        val = abs(row[j])
        if val == 1:
            return n
        if val and val < mi_val:
            mi_val = val
            mi_i = n
    return mi_i

def move_pivot_row_to_top(M, i, j):
    """
    Move the pivot row to the top.

    Args:
        M (numpy.ndnp.array): The matrix.
        i (int): The current row index.
        j (int): The current column index.

    Returns:
        numpy.ndnp.array: The matrix with the pivot row moved to the top.
    """
    p = pivot_row_index(M, i, j)
    if p:
        M[[i, p]] = M[[p, i]]
    return M

def move_null_rows_to_bottom(M):
    """
    Move null rows to the bottom.

    Args:
        M (numpy.ndnp.array): The matrix.

    Returns:
        numpy.ndnp.array: The matrix with null rows moved to the bottom.
    """
    null_row_indices = np.where(~M.any(axis=1))[0]
    M = np.delete(M, null_row_indices, axis=0)
    null_rows = np.zeros((len(null_row_indices), M.shape[1]))
    M = np.concatenate((M, null_rows))
    return M

def echelon_form(X):
    """
    Convert a matrix to echelon form. Using Gaussian elimination

    Args:
        X (numpy.ndnp.array): The matrix.

    Returns:
        numpy.ndnp.array: The matrix in echelon form.
    """
    M = np.copy(X)
    p = 0
    r = M.shape[0]
    c = M.shape[1]
    M = move_pivot_row_to_top(M, 0, 0)
    for i in range(r - 1):
        c_row = M[i]
        for j in range(i + 1, r):
            n_row = M[j]
            x, y = c_row[p], n_row[p]
            if y != 0:
                if x == -y:
                    M[j] = c_row + n_row
                else:
                    k = -y / x
                    M[j] = c_row * k + n_row
        M = move_null_rows_to_bottom(M)
        if is_echelon_form(M):
            return M
        p += 1 if p < c - 1 else 0
        M = move_pivot_row_to_top(M, i + 1, p)
    return M

D = np.array(
    [
        [0, 0, 6],
        [2, 0, -6],
        [0, 2, 6],
        [-1, -2, -3],
        [1, 2, 3],
    ]
)

print(echelon_form(D))

[[-1. -2. -3.]
 [ 0.  2.  6.]
 [ 0.  0.  6.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


# Unidad 1

## Ejercicio 5
Dadas las siguientes matrices:

In [ ]:
A = np.array([
    [-2, 0],
    [1, -1],
    [-3, 2]])
B = np.array([
    [3, -3],
    [0, 3],
    [-3, 3]])
C = np.array([
    [2, 3, 1],
    [1, 3, 2]])
D = np.array([
    [1, 3, 5],
    [2, 4, 6],
    [0, -1, 2]])
E = np.array([
    [2, -4],
    [1, 0]])

Realizar, si es posible, las siguientes operaciones, indicando el orden de la matriz resultante:

- $A + \frac{1}{3}B$

In [ ]:
A + (1/3) * B

- $C^T + B$

In [ ]:
C.T + B

- $C \cdot A - E^T$

In [ ]:
C @ A - E.T

- $(A+B)\cdot C$

In [ ]:
(A + B) @ C

- $B\cdot C + D^T$

In [ ]:
(B @ C) + D.T

## Ejercicio 6
Calcular el determinante, si es posible, de las siguientes matrices:

In [ ]:
A = np.array([
    [2, 0],
    [1, 2]])
B = np.array([
    [4, -3],
    [2, -1]])
C = np.array([
    [3, 2, 1],
    [0, 1, 3],
    [-3, 4, -2]])
D = np.array([
    [3, 0, 2, 1],
    [1, 1, 0, 3],
    [0, 2, 4, 4]])
E = np.array([
    [1, 1, -1, 0],
    [0, 1, 1, 1],
    [0, 1, 0, -3],
    [-1, 1, 2, 0]])
F = np.array([
    [2, 4, -1, 2],
    [1, 0, 1, -1],
    [0, 2, -1, -1],
    [1, -2, 1, 0]])

Determinantes:

In [ ]:
print(f"det(A) = {np.linalg.det(A)}\tdet(B) = {np.linalg.det(B)}\tdet(C) = {np.linalg.det(C):.1f}\tdet(E) = {np.linalg.det(E)}\tdet(F) = {np.linalg.det(F)}")

## Ejercicio 8
Calcular el rango de las siguientes matrices por escalonamiento:

In [ ]:
A = np.array([
    [1, -1, -1],
    [0, 1, 0],
    [1, 1, 0]])
B = np.array([
    [1, 2, 3, 0],
    [-1, 2, -3, 1],
    [2, 0, 6, -1]])
C = np.array([
    [-1, 2, -1, 0],
    [0, -1, 2, 1],
    [-1, 1, 1, 1],
    [-1, 0, 3, 2]])
D = np.array([
    [1, 2, 3],
    [0, 2, 6],
    [-1, -2, -3],
    [0, 0, 6],
    [2, 0, -6]])

Rangos:

In [ ]:
print(f"rg(A) = {rank(A)}\trg(B) = {rank(B)}\trg(C) = {rank(C)}\trg(D) = {rank(D)}")

## Ejercicio 10
1) Clasificar usando el teorema de Rouchê Frobenius.
2) Determinar el conjunto solución aplicando el Método de eliminación de Gauss.

In [ ]:
def roucheFrobenius(sol):
    if not sol:
        return "Sistema compatible indeterminado"
    else:
        return "Sistema compatible determinado"

def conj_sol(sol):
    s = ""
    ln = len(sol.values())
    val_list = list(sol.values()) 

    for i in range(ln):
        val = val_list[i]
        if i == ln - 1:
            s += f"{val}"
        else:
            s += f"{val}, "
    return s

x, y, z = symbols('x y z')

A = (
    Eq(x - y, 0),
    Eq(x + 3*y, 4),
    Eq(4*x - 2*y, 3)
)
sol_A = solve(A, (x, y)) # Soluciones infinitas
print(f"a) S = {solve(A, (x, y))}")

B = (
    Eq(x - 3*y + 2*z, 5),
    Eq(x + 2*y + 3*z, 7),
    Eq(2*x - y + z, 4)
)
sol_B = solve(B, (x, y, z))
conj_B = conj_sol(sol_B)
clas_B = roucheFrobenius(sol_B)

print(f"b) {clas_B}\n\tS = ({conj_B})")